// Code generated by mockery v1.0.0
package mocks

import instructions "github.com/windler/awesm/aml/instructions"
import mock "github.com/stretchr/testify/mock"

// ForkJoinFactory is an autogenerated mock type for the ForkJoinFactory type
type ForkJoinFactory struct {
	mock.Mock
}

// GetPattern provides a mock function with given fields:
func (_m *ForkJoinFactory) GetPattern() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewForkNode provides a mock function with given fields: name
func (_m *ForkJoinFactory) NewForkNode(name string) *instructions.AMLInstruction {
	ret := _m.Called(name)

	var r0 *instructions.AMLInstruction
	if rf, ok := ret.Get(0).(func(string) *instructions.AMLInstruction); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*instructions.AMLInstruction)
		}
	}

	return r0
}

// NewJoinNode provides a mock function with given fields: name, forkNode
func (_m *ForkJoinFactory) NewJoinNode(name string, forkNode *instructions.AMLInstruction) *instructions.AMLInstruction {
	ret := _m.Called(name, forkNode)

	var r0 *instructions.AMLInstruction
	if rf, ok := ret.Get(0).(func(string, *instructions.AMLInstruction) *instructions.AMLInstruction); ok {
		r0 = rf(name, forkNode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*instructions.AMLInstruction)
		}
	}

	return r0
}

// ProvidesPathLabels provides a mock function with given fields:
func (_m *ForkJoinFactory) ProvidesPathLabels() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
